Hotfix/ Permisos votaciones, eliminar y censo
3ralon/decide-single-zambrano pull request #80
Opened 2023-12-04 15:14 UTC by silvglad

Como os comenté en el último pull request relacionado a esta feature, ahora que pude trabajar con los avances en la autenticación he podido implementar los fixes a los permisos. Además, he visto útil añadir la posibilidad de eliminar votaciones/preguntas, así como editar el censo de una votación cuando se inicia

El único problema que he detectado es referente al inicio de sesión, puesto que al entrar a las secciones de votaciones o preguntas, a veces el atributo request detecta un usuario distinto debido a como funcionan las APIview, intentaré echarle un vistazo más a fondo tras el merge

2023-12-04 15:27 UTC, claugp06 approved these changes
Buen trabajo. Desde mi parte veo todo bien.

2023-12-05 13:15 UTC, silvglad commented
Buenas, con el último commit he solucionado el problema con el inicio de sesión entre views que comenté al principio de la pull request. Asimismo, he modificado la homepage para que, cuando estés autenticado, solo te aparezcan las votaciones en las cuales estés incluido en su censo

2023-12-08 16:05 UTC, 3ralon requested changes
Buenas @silvglad, no me parece mal. Pero el testigo del actions ha saltado. Corrige lo que esté haciendo al actions fallar y entonces te acepto la PR.

2023-12-09 12:54 UTC, laurolmer approved these changes
Por mi parte bien, aunque opino igual que nuestro compañero Alberto

2023-12-09 19:37 UTC, MarioArocaPaez commented
He estado arreglandolo, ahora mismo el error por el que se queja es por un Trailing whitespace, no me parece muy importante
Esto nos va a seguir pasando, tenemos que ver lo de intalar el linter para evitar estas cosas
![imagen](https://github.com/3ralon/decide-single-zambrano/assets/73229438/54fb1610-b6ff-425c-a304-e09acf058218)

2023-12-09 20:02 UTC, claugp06 commented
@MarioArocaPaez Si habría que instalar el linter cuanto antes. Por el resto si lo has conseguido arreglar perfecto!!

2023-12-10 17:05 UTC, silvglad commented
Sí, habría que mirar de tener un linter o modificar los checks de Codacy para que no salte por problemas de code style. En principio, hago merge ya que veo que no hay otros problemas con la rama

2023-12-10 17:05 UTC, merged